version: '3.9'
services:
  ocserv:
    image: etoosamoe/ocserv
    restart: unless-stopped
    container_name: ocserv
    hostname: www.example.com
    environment:
      - ENABLE_EXPORTER=1
    ports:
      - 443:443
      - 443:443/udp
    volumes:
      - "/etc/ocserv:/etc/ocserv"
      - "/etc/ssl/kefile.key:/etc/ocserv/certs/server-key.pem:ro"
      - "/etc/ssl/crtfile.crt:/etc/ocserv/certs/server-cert.pem:ro"
    cap_add:
      - NET_ADMIN
    security_opt:
      - no-new-privileges